
import { toast } from 'sonner';
import { supabase } from '@/integrations/supabase/client';

export interface AstrologyResult {
  birthSign: string;
  nakshatra: string;
  luckyNumbers: number[];
  luckyColors: string[];
  suggestedNames: Array<{
    name: string;
    meaning: string;
    origin: string;
    score: number;
  }>;
  planetaryInfluence: string;
  recommendations: string[];
}

export const generatePDF = (result: AstrologyResult) => {
  try {
    // Get top 3 names
    const topThreeNames = result.suggestedNames
      .sort((a, b) => b.score - a.score)
      .slice(0, 3);

    // Create HTML content for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>AstroName Oracle - Astrological Name Report</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
          .header { text-align: center; border-bottom: 2px solid #6366f1; padding-bottom: 20px; margin-bottom: 30px; }
          .section { margin-bottom: 25px; }
          .birth-chart { background: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
          .top-names { background: #fef3c7; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
          .name-card { border: 1px solid #d1d5db; padding: 15px; margin: 10px 0; border-radius: 6px; }
          .score { color: #6366f1; font-weight: bold; }
          .guidance { background: #ecfdf5; padding: 15px; border-radius: 8px; }
          h1 { color: #6366f1; }
          h2 { color: #059669; }
          h3 { color: #7c3aed; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>⭐ AstroName Oracle - Astrological Name Report ⭐</h1>
          <p>Ancient Vedic Wisdom for Modern Names</p>
        </div>

        <div class="section birth-chart">
          <h2>🌟 वैदिक जन्म कुंडली (Vedic Birth Chart)</h2>
          <p><strong>राशि (Rashi):</strong> ${result.birthSign}</p>
          <p><strong>नक्षत्र (Nakshatra):</strong> ${result.nakshatra}</p>
          <p><strong>Lucky Numbers:</strong> ${result.luckyNumbers.join(', ')}</p>
          <p><strong>Lucky Colors:</strong> ${result.luckyColors.join(', ')}</p>
          <p><strong>Planetary Influence:</strong> ${result.planetaryInfluence}</p>
        </div>

        <div class="section top-names">
          <h2>👑 Top 3 Recommended Names</h2>
          ${topThreeNames.map((name, index) => `
            <div class="name-card">
              <h3>Rank #${index + 1}: ${name.name}</h3>
              <p><strong>Meaning:</strong> ${name.meaning}</p>
              <p><strong>Origin:</strong> ${name.origin}</p>
              <p><strong>Astrology Score:</strong> <span class="score">${name.score}/10</span></p>
            </div>
          `).join('')}
        </div>

        <div class="section">
          <h2>📝 All Name Suggestions (${result.suggestedNames.length} Names)</h2>
          ${result.suggestedNames.map(name => `
            <div class="name-card" style="display: inline-block; width: 45%; margin: 5px;">
              <strong>${name.name}</strong> - ${name.meaning} 
              <span class="score">(${name.score}/10)</span>
            </div>
          `).join('')}
        </div>

        <div class="section guidance">
          <h2>🔮 वैदिक मार्गदर्शन (Vedic Guidance)</h2>
          ${result.recommendations.map(rec => `<p>• ${rec}</p>`).join('')}
        </div>

        <div class="section" style="text-align: center; margin-top: 40px; border-top: 1px solid #d1d5db; padding-top: 20px;">
          <p><em>Generated by AstroName Oracle ✨</em></p>
          <p>Visit us for more astrological insights and consultations</p>
        </div>
      </body>
      </html>
    `;

    // Create and download PDF
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AstroName-Oracle-Report-${new Date().getTime()}.html`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
    
    toast.success('Report downloaded successfully!');
  } catch (error) {
    console.error('Error generating PDF:', error);
    toast.error('Failed to generate PDF. Please try again.');
  }
};

export const shareViaEmail = async (result: AstrologyResult, email: string) => {
  try {
    const { data, error } = await supabase.functions.invoke('send-report-email', {
      body: { email, result }
    });

    if (error) throw error;

    toast.success('📧 EMAIL SENT SUCCESSFULLY!', {
      style: {
        fontSize: '16px',
        fontWeight: 'bold',
        padding: '16px',
      }
    });
  } catch (error) {
    console.error('Error sending email:', error);
    toast.error('Failed to send email. Please try again.');
  }
};
