
import { AstrologyResult } from './astrology';

export const generatePDF = (result: AstrologyResult, babyName?: string) => {
  const content = `
    StarName Oracle - Astrological Name Report
    
    Birth Sign: ${result.birthSign}
    ${babyName ? `Baby Name: ${babyName}` : ''}
    
    Lucky Numbers: ${result.luckyNumbers.join(', ')}
    Lucky Colors: ${result.luckyColors.join(', ')}
    
    Planetary Influence:
    ${result.planetaryInfluence}
    
    Suggested Names (${result.suggestedNames.length} total):
    ${result.suggestedNames.map((name, index) => 
      `${index + 1}. ${name.name} (${name.origin})
         Meaning: ${name.meaning}
         Score: ${name.score}/10`
    ).join('\n\n')}
    
    Cosmic Recommendations:
    ${result.recommendations.map((rec, index) => 
      `${index + 1}. ${rec}`
    ).join('\n')}
    
    Generated by StarName Oracle
    May the stars guide you to the perfect name ✨
  `;

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `starname-oracle-report-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const shareViaGmail = (result: AstrologyResult, babyName?: string) => {
  const subject = encodeURIComponent('StarName Oracle - Astrological Name Report');
  const body = encodeURIComponent(`
Dear Friend,

I wanted to share this beautiful astrological name report from StarName Oracle:

Birth Sign: ${result.birthSign}
${babyName ? `Baby Name: ${babyName}` : ''}

Top 3 Suggested Names:
${result.suggestedNames.slice(0, 3).map((name, index) => 
  `${index + 1}. ${name.name} - ${name.meaning} (${name.origin})`
).join('\n')}

${result.planetaryInfluence}

View the complete report with all ${result.suggestedNames.length} name suggestions at StarName Oracle.

Blessings,
StarName Oracle ✨
  `);
  
  const gmailUrl = `https://mail.google.com/mail/u/0/?view=cm&fs=1&su=${subject}&body=${body}`;
  window.open(gmailUrl, '_blank');
};
